services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment-booking-api
    ports:
      - "8000:80"
    volumes:  
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: booking_open_source
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    networks:
      - appnet


  db:
    image: mysql:5.7
    container_name: appointment-booking-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking_open_source
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: appointment-booking-pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
