<?php

$commonProfileFields = [
    'student_number',
    'course',
    'college',
    'year_level',
    'address',
    'guardian_name',
    'guardian_contact',
];

$config = [
    'statuses' => [
        'pending_admin_approval' => 'Pending Admin Approval',
        'approved_for_form_access' => 'Approved for Form Access',
        'for_signatory' => 'For Signatory',
        'for_notary' => 'For Notary',
        'appointment_scheduled' => 'Appointment Scheduled',
        'under_review' => 'Under Review',
        'completed' => 'Completed',
        'rejected' => 'Rejected',
    ],
    'appointments' => [
        'daily' => 50,
        'morning' => 25,
        'afternoon' => 25,
        'lookahead_days' => 10,
        'sessions' => [
            'morning' => 'Morning Session',
            'afternoon' => 'Afternoon Session',
        ],
    ],
    'office_locations' => [
        'guidance' => [
            'name' => 'Guidance and Testing Office',
            'description' => 'Handles guidance endorsements and student counseling-related approvals.',
        ],
        'vpsd' => [
            'name' => 'Office of the Vice-President for Student Development (VPSD)',
            'description' => 'Primary approving office for student development transactions.',
        ],
        'vpas' => [
            'name' => 'Office of the Vice-President for Academic Services (VPAS)',
            'description' => 'Handles academic-service approvals such as excused absences.',
        ],
        'dean' => [
            'name' => "Dean's Office",
            'description' => 'College-level approval office for student and activity transactions.',
        ],
        'student_org' => [
            'name' => 'Director of Student Organizations and Activities',
            'description' => 'Coordinates organization clearances, activities, and student organization approvals.',
        ],
        'notary' => [
            'name' => 'Attorney / Notary Office',
            'description' => 'Required for notarized affidavits and guardianship-related documents.',
        ],
    ],
    'handbook' => [
        'title' => 'University Student Handbook',
        'summary' => 'Students may use this module for handbook guidance, process reminders, and transaction compliance notes.',
        'sections' => [
            [
                'title' => 'Student Conduct',
                'body' => 'Review expected behavior, disciplinary processes, and reporting procedures before filing complaint or disciplinary forms.',
            ],
            [
                'title' => 'Clearance and Accountability',
                'body' => 'Clearance tagging is used in DOCUMATE to validate whether a student may proceed with selected VPSD transactions.',
            ],
            [
                'title' => 'Student Assistantship',
                'body' => 'Student assistantship requests require supporting documents, recommendations, and parent consent before final endorsement.',
            ],
            [
                'title' => 'Document Handling',
                'body' => 'Official forms must be completed, manually signed where required, and brought to the scheduled DOCUMATE appointment for processing.',
            ],
        ],
    ],
    'transaction_types' => [
        [
            'code' => 'F-SDM-001',
            'name' => 'Admission Slip Form',
            'slug' => 'admission-slip-form',
            'short_name' => 'Admission Slip',
            'description' => 'Admission processing slip routed through guidance and VPSD.',
            'required_signatories' => ['Guidance Counselor', 'VPSD'],
            'workflow_steps' => [
                'Accomplish the Admission Slip Form with all required information.',
                'Secure signatures from the Guidance Counselor and the VPSD.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 1,
        ],
        [
            'code' => 'F-SDM-002',
            'name' => 'Permit to Enter the Campus / To Attend Classes Form',
            'slug' => 'permit-to-enter-campus',
            'short_name' => 'Campus/Class Permit',
            'description' => 'Student permit for campus or class attendance with VPSD approval.',
            'required_signatories' => ['VPSD'],
            'workflow_steps' => [
                'Accomplish the permit form with complete details.',
                'Proceed to VPSD and secure the required signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 2,
        ],
        [
            'code' => 'F-SDM-003',
            'name' => 'Request for Renewal of Student Old ID Form',
            'slug' => 'student-id-renewal',
            'short_name' => 'Student ID Renewal',
            'description' => 'Request for renewal or reprinting of a student ID.',
            'required_signatories' => ['VPSD'],
            'workflow_steps' => [
                'Accomplish the request for renewal or reprinting of student ID form.',
                'Proceed to VPSD and secure the required signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 3,
        ],
        [
            'code' => 'F-SDM-004',
            'name' => 'Affidavit of Loss Form',
            'slug' => 'affidavit-of-loss',
            'short_name' => 'Affidavit of Loss',
            'description' => 'Notarized affidavit for lost school-related documents or items.',
            'required_signatories' => ['Notary Public'],
            'workflow_steps' => [
                'Accomplish the Affidavit of Loss Form with all required information.',
                'Proceed to an attorney or notary office to have the form notarized.',
                'Scan the accomplished and notarized form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'requires_notary' => true,
            'sort_order' => 4,
        ],
        [
            'code' => 'F-SDM-005',
            'name' => 'Student Appointment Slip Form',
            'slug' => 'student-appointment-slip',
            'short_name' => 'Appointment Slip',
            'description' => 'Student appointment request routed through VPSD.',
            'required_signatories' => ['VPSD'],
            'workflow_steps' => [
                'Accomplish the Student Appointment Slip Form.',
                'Proceed to VPSD and secure the required signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 5,
        ],
        [
            'code' => 'F-SDM-006',
            'name' => 'Permit to Conduct an In-Campus Student Activity Form',
            'slug' => 'in-campus-activity-permit',
            'short_name' => 'In-Campus Activity Permit',
            'description' => 'Permission form for in-campus student activities.',
            'required_signatories' => ['Organization Adviser / Academic Chair', 'VPSD'],
            'workflow_steps' => [
                'Accomplish the in-campus student activity form.',
                'Secure signatures from the respective Organization Adviser or Academic Chair and the VPSD.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 6,
        ],
        [
            'code' => 'F-SDM-007',
            'name' => 'Permit to Conduct / Participate in a Non-Curricular Off-Campus Student Activity Form',
            'slug' => 'off-campus-activity-permit',
            'short_name' => 'Off-Campus Activity Permit',
            'description' => 'Permission form for non-curricular off-campus student activities.',
            'required_signatories' => ['Organization Adviser / Academic Chair', 'Dean', 'VPSD'],
            'workflow_steps' => [
                'Accomplish the non-curricular off-campus activity form.',
                'Secure signatures from the respective adviser or chair, the Dean, and the VPSD.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 7,
        ],
        [
            'code' => 'F-SDM-008',
            'name' => 'Disciplinary Case Report Form',
            'slug' => 'disciplinary-case-report',
            'short_name' => 'Disciplinary Case Report',
            'description' => 'Formal reporting form for disciplinary cases.',
            'required_signatories' => [],
            'workflow_steps' => [
                'Accomplish the Disciplinary Case Report Form.',
                'Scan the accomplished form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 8,
        ],
        [
            'code' => 'F-SDM-009',
            'name' => 'Request for Excused Absence Form',
            'slug' => 'request-for-excused-absence',
            'short_name' => 'Excused Absence',
            'description' => 'Excused absence request requiring academic and student development sign-off.',
            'required_signatories' => ['VPSD', 'Dean', 'VPAS'],
            'workflow_steps' => [
                'Accomplish the Request for Excused Absence Form.',
                'Secure signatures from the VPSD, the Dean, and the VPAS.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 9,
        ],
        [
            'code' => 'F-SDM-010',
            'name' => 'Disciplinary Action Slip Form',
            'slug' => 'disciplinary-action-slip',
            'short_name' => 'Disciplinary Action Slip',
            'description' => 'Action slip requiring issuer and VPSD signatures.',
            'required_signatories' => ['Faculty / Security Guard / Personnel', 'VPSD'],
            'workflow_steps' => [
                'Accomplish the Disciplinary Action Slip Form.',
                'Secure the signature of the issuing faculty, security guard, or personnel.',
                'Proceed to VPSD and secure the required signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 10,
        ],
        [
            'code' => 'F-SDM-011',
            'name' => 'Disciplinary Referral Slip Form',
            'slug' => 'disciplinary-referral-slip',
            'short_name' => 'Disciplinary Referral Slip',
            'description' => 'Referral slip signed by the issuing personnel.',
            'required_signatories' => ['Faculty / Security Guard / Personnel'],
            'workflow_steps' => [
                'Accomplish the Disciplinary Referral Slip Form.',
                'Secure the signature of the issuing faculty, security guard, or personnel.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 11,
        ],
        [
            'code' => 'F-SDM-012',
            'name' => 'Lost / Found Item Form',
            'slug' => 'lost-found-item-form',
            'short_name' => 'Lost / Found Item',
            'description' => 'Tracking and claim form for lost and found items.',
            'required_signatories' => ['Claimant'],
            'workflow_steps' => [
                'Accomplish the Lost / Found Item Form.',
                'Secure the signature of the person who claimed the item.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 12,
        ],
        [
            'code' => 'F-SDM-013',
            'name' => 'Parents / Guardians Permit Form',
            'slug' => 'parents-guardians-permit',
            'short_name' => 'Parents / Guardians Permit',
            'description' => 'Parent or guardian permit requiring signature and notarization.',
            'required_signatories' => ['Parent / Guardian', 'Notary Public'],
            'workflow_steps' => [
                'Accomplish the Parents / Guardians Permit Form.',
                'Secure the signature of the parent or guardian.',
                'Proceed to a notary or attorney office for notarization.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'requires_notary' => true,
            'sort_order' => 13,
        ],
        [
            'code' => 'F-SDM-014',
            'name' => 'Student Advisement Form',
            'slug' => 'student-advisement',
            'short_name' => 'Student Advisement',
            'description' => 'Advisement form signed by the issuing personnel.',
            'required_signatories' => ['Faculty / Security Guard / Personnel'],
            'workflow_steps' => [
                'Accomplish the Student Advisement Form.',
                'Secure the signature of the issuing faculty, security guard, or personnel.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 14,
        ],
        [
            'code' => 'F-SDM-015',
            'name' => 'Application for Student Assistantship Form',
            'slug' => 'student-assistantship-application',
            'short_name' => 'Assistantship Application',
            'description' => 'Application form for student assistantship screening.',
            'required_signatories' => ['Office of the Vice-President'],
            'workflow_steps' => [
                'Accomplish the Application for Student Assistantship Form.',
                'Present GPA eligibility, good moral character, and two recommendations to the Office of the Vice-President.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 15,
        ],
        [
            'code' => 'F-SDM-016',
            'name' => "Parent's Consent for Student Assistantship Form",
            'slug' => 'parent-consent-student-assistantship',
            'short_name' => 'Parent Consent',
            'description' => 'Parent or guardian consent for student assistantship.',
            'required_signatories' => ['Parent / Guardian'],
            'workflow_steps' => [
                "Accomplish the Parent's Consent for Student Assistantship Form.",
                'Secure the signature of the parent or guardian.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 16,
        ],
        [
            'code' => 'F-SDM-017',
            'name' => 'Recommendation for Student Assistantship Form',
            'slug' => 'recommendation-student-assistantship',
            'short_name' => 'Assistantship Recommendation',
            'description' => 'Faculty recommendation form for student assistantship.',
            'required_signatories' => ['Faculty Member'],
            'workflow_steps' => [
                'Accomplish the Recommendation for Student Assistantship Form.',
                'Proceed to the respective faculty unit and secure the faculty signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 17,
        ],
        [
            'code' => 'F-SDM-018',
            'name' => 'Student Assistantship Performance Evaluation Form',
            'slug' => 'assistantship-performance-evaluation',
            'short_name' => 'Assistantship Evaluation',
            'description' => 'Performance evaluation form for student assistants.',
            'required_signatories' => ['Supervisor / Rater'],
            'workflow_steps' => [
                'Accomplish the Student Assistantship Performance Evaluation Form.',
                'Secure the signature of the supervisor or rater.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 18,
        ],
        [
            'code' => 'F-SDM-019',
            'name' => 'Student Assistantship Endorsement Form',
            'slug' => 'assistantship-endorsement',
            'short_name' => 'Assistantship Endorsement',
            'description' => 'Endorsement form for student assistantship routed through VPSD.',
            'required_signatories' => ['VPSD'],
            'workflow_steps' => [
                'Accomplish the Student Assistantship Endorsement Form.',
                'Proceed to VPSD and secure the required signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 19,
        ],
        [
            'code' => 'F-SDM-020',
            'name' => 'General Student Clearance',
            'slug' => 'general-student-clearance',
            'short_name' => 'General Clearance',
            'description' => 'General student clearance covering organizational and library signatories.',
            'required_signatories' => [
                'Academic Organization Treasurer',
                'Non-Academic Organization Treasurer',
                'Year Level Organization Treasurer',
                'SSC President',
                'Director of Student Organizations and Activities',
                'College Chief Librarian',
                'Academic Organization Adviser',
                'Non-Academic Organization Adviser',
                'Year Level Adviser',
                'Respective Organization',
                'VPSD',
            ],
            'workflow_steps' => [
                'Accomplish the General Student Clearance form.',
                'Secure the listed organizational, librarian, adviser, and organization signatures.',
                'Proceed to VPSD for final signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 20,
        ],
        [
            'code' => 'F-SDM-021',
            'name' => 'Clearance for Organization Officer',
            'slug' => 'clearance-for-organization-officer',
            'short_name' => 'Organization Officer Clearance',
            'description' => 'Clearance form for organization officers.',
            'required_signatories' => [
                'SSC Treasurer',
                'SSC President',
                'College Chief Librarian',
                'SSC Secretary',
                'Director of Student Organizations and Activities',
                'Respective Organization',
                'VPSD',
            ],
            'workflow_steps' => [
                'Accomplish the Clearance for Organization Officer form.',
                'Secure the required SSC, librarian, student organizations, and organization signatures.',
                'Proceed to VPSD for final signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 21,
        ],
        [
            'code' => 'F-SDM-022',
            'name' => 'Clearance for SSC Officers',
            'slug' => 'clearance-for-ssc-officers',
            'short_name' => 'SSC Officers Clearance',
            'description' => 'Clearance for SSC or student publication officers.',
            'required_signatories' => [
                'SSC Treasurer / SPO Managing Editor',
                'SSC President / SPO Editor-in-Chief',
                'College Chief Librarian',
                'Director of Student Organizations and Activities',
                'SSC Secretary',
                'SSC / SPO Adviser',
                'University Accountant',
                'Organization',
                'VPSD',
            ],
            'workflow_steps' => [
                'Accomplish the Clearance for SSC Officers form.',
                'Secure the required SSC, SPO, librarian, accountant, and organization signatures.',
                'Proceed to VPSD for final signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 22,
        ],
        [
            'code' => 'F-SDM-023',
            'name' => 'Student Complaint / Grievance Form',
            'slug' => 'student-complaint-grievance',
            'short_name' => 'Complaint / Grievance',
            'description' => 'Student complaint or grievance submission form.',
            'required_signatories' => ['Parent / Guardian'],
            'workflow_steps' => [
                'Accomplish the Student Complaint / Grievance Form.',
                'Secure the signature of the parent or guardian.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 23,
        ],
        [
            'code' => 'F-SDM-024',
            'name' => 'Model Student Faculty Peer Rating Form',
            'slug' => 'model-student-faculty-peer-rating',
            'short_name' => 'Model Student Rating',
            'description' => 'Faculty or peer rating form for model student evaluation.',
            'required_signatories' => ['Rater'],
            'workflow_steps' => [
                'Accomplish the Model Student Faculty Peer Rating Form.',
                'Secure the signature of the rater.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 24,
        ],
        [
            'code' => 'F-SDM-025',
            'name' => 'Model Student Nomination Form',
            'slug' => 'model-student-nomination',
            'short_name' => 'Model Student Nomination',
            'description' => 'Nomination form for model student endorsement.',
            'required_signatories' => ['VPSD'],
            'workflow_steps' => [
                'Accomplish the Model Student Nomination Form.',
                'Proceed to VPSD and secure the required signature.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 25,
        ],
        [
            'code' => 'F-SDM-026',
            'name' => 'Graduate Model Student Interview Rating Form',
            'slug' => 'graduate-model-student-interview-rating',
            'short_name' => 'Interview Rating',
            'description' => 'Interview or talent presentation rating form for model student selection.',
            'required_signatories' => ['Interviewer'],
            'workflow_steps' => [
                'Accomplish the Graduate Model Student Interview Rating Form.',
                'Secure the signature of the interviewer.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 26,
        ],
        [
            'code' => 'F-SDM-027',
            'name' => 'YMCA Nomination Form',
            'slug' => 'ymca-nomination-form',
            'short_name' => 'YMCA Nomination',
            'description' => 'Nomination form for YMCA student award consideration.',
            'required_signatories' => ['Nominator'],
            'workflow_steps' => [
                'Accomplish the YMCA Nomination Form.',
                'Secure the signature of the nominator.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 27,
        ],
        [
            'code' => 'F-SDM-028',
            'name' => 'YMCA Faculty Peer Rating Form',
            'slug' => 'ymca-faculty-peer-rating',
            'short_name' => 'YMCA Rating',
            'description' => 'Faculty or peer rating form for YMCA student award evaluation.',
            'required_signatories' => ['Rater'],
            'workflow_steps' => [
                'Accomplish the YMCA Faculty Peer Rating Form.',
                'Secure the signature of the rater.',
                'Scan the accomplished and signed form.',
                'Upload the scanned copy through DOCUMATE OCR.',
            ],
            'required_profile_fields' => $commonProfileFields,
            'sort_order' => 28,
        ],
    ],
];

$config['transaction_types'] = array_map(function (array $type) {
    $type['workflow_steps'] = array_map(function (string $step) {
        if (str_starts_with($step, 'Scan the ')) {
            return 'Prepare the completed form and keep the original copy ready for your scheduled DOCUMATE appointment.';
        }

        if ($step === 'Upload the scanned copy through DOCUMATE OCR.') {
            return 'Book your DOCUMATE appointment and visit the office on your confirmed schedule.';
        }

        return $step;
    }, $type['workflow_steps'] ?? []);

    return $type;
}, $config['transaction_types']);

return $config;
